version: "3"
tasks:
  up:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - echo "Taking down containers..."
      - sudo docker-compose down
      - echo "Done. Bringing up containers..."
      - sudo docker-compose up -d --build

  down:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - sudo docker-compose down

  clean-db:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - sudo rm -rf mysql_data/

  logs:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - sudo docker-compose logs -f

  update:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git pull
      - task: up

