@hostname = localhost 
@backend_port = 8888
###
GET http://{{hostname}}:{{backend_port}}/data

### 
GET http://{{hostname}}:{{backend_port}}/exams


###
POST http://{{hostname}}:{{backend_port}}/data
Content-Type: application/json

{
  "exam": "SLY-N41",
  "content": "What is the capital of Sweden?",
  "source": "",
  "question_number": 998,
  "answers": [
    {
      "content": "Stockholm",
      "correct_answer": true
    },
    {
      "content": "Barcelona"
    },
    {
      "content": "Madrid",
       "correct_answer": true
    },
    {
      "content": "Helsinki"
    }
  ]
}
