@hostname = localhost 
@backend_port = 3000
###
GET http://{{hostname}}:{{backend_port}}/data

###
POST http://{{hostname}}:{{backend_port}}/data
Content-Type: application/json

{
  "exam": "SLY-N41",
  "content": "What is the capital of Sweden?",
  "answers": [
    {
      "content": "Stockholm",
      "correct": true
    },
    {
      "content": "Barcelona"
    },
    {
      "content": "Madrid"
    },
    {
      "content": "Helsinki"
    }
  ]
}
